function write_schism_source_nc(Mobj, D, tracer_list)
% Write the source.nc file for SHCISM
% 
%% Syntax
% write_schism_source_nc(Mobj, D)
% write_schism_source_nc(Mobj, D, tracer_list)
% 
%% Description 
% write_schism_source_nc(Mobj, D) writes the source.nc file.
% write_schism_source_nc(Mobj, D, tracer_list) specifies the tracers to be written.
%
%% Input Arguments
% Mobj - the mesh object; datatruct.
%       the datastruct used to store the mesh info.
% D - source data; datastruct
%       the datastruct generated by 'prep_river_source', which contains the
%       river source data with specific format. 
% tracer_list - tracer variables; cell
%       the tracers to be written. Default: tracer_list = {'temp', 'salt'}.
%
%% Output Arguments
% None
%
%% Author Info
% Created by Wenfan Wu, Virginia Institute of Marine Science in 2021.
% Last Updated on 6 May 2025.
% Email: wwu@vims.edu
% 
% See also: add_river_inputs and prep_river_source

%% Parse inputs
if nargin < 2; tracer_list = {'temp', 'salt'}; end
tracer_list = lower(tracer_list);
tracer_list(contains(tracer_list, 'runoff')) = [];

% check the tracer order
ind_tracers = arrayfun(@(x) find(contains(lower(Mobj.active_tracers), x)), tracer_list);
if ~issorted(ind_tracers)
    error('the tracer order is not right, please check!')
else
    disp('the tracer order is correct')
end
%% Load data 
% nsources, nsinks, ntracers
ntracers = numel(tracer_list);
nsources = max(1, length(D.source_elems));
nsinks = max(1,length(D.sink_elems));
ntimes = length(D.vsource.time);

time_step_vsource = D.vsource.dt;
time_step_msource = D.msource.dt;
time_step_vsink= D.vsink.dt;

time_msource = seconds(D.msource.time-D.msource.time(1));
time_vsource = seconds(D.vsource.time-D.vsource.time(1));
time_vsink = seconds(D.vsink.time-D.vsink.time(1));

source_elem = D.source_elems;
sink_elem = D.sink_elems;
if isempty(sink_elem); sink_elem = 1; end

msource = [];
for ii = 1:length(tracer_list)
    tracer_name = tracer_list{ii};
    tracer_data = D.msource.(tracer_name);
    msource = cat(3, msource, tracer_data);
end
msource = permute(msource, [2 3 1]);  % nsources * ntracers * ntimes
vsource = D.vsource.runoff';
vsink = D.vsink.runoff(:,1)';

%% Begin to write (source.nc )
filepath = fullfile(Mobj.aimpath, 'source.nc');
if exist(filepath,'file')==2; delete(filepath); end

nccreate(filepath,'time_step_vsource','Datatype','double','Format','netcdf4')
ncwrite(filepath,'time_step_vsource', time_step_vsource);

nccreate(filepath,'time_step_msource','Datatype','double','Format','netcdf4')
ncwrite(filepath,'time_step_msource', time_step_msource);

nccreate(filepath,'time_step_vsink','Datatype','double','Format','netcdf4')
ncwrite(filepath,'time_step_vsink', time_step_vsink);

nccreate(filepath,'time_vsource','Dimensions',{'time_vsource', ntimes},'Datatype','double','Format','netcdf4')
ncwrite(filepath,'time_vsource', time_vsource);

nccreate(filepath,'time_msource','Dimensions',{'time_msource', ntimes},'Datatype','double','Format','netcdf4')
ncwrite(filepath,'time_msource', time_msource);

nccreate(filepath,'time_vsink','Dimensions',{'time_vsink', ntimes},'Datatype','double','Format','netcdf4')
ncwrite(filepath,'time_vsink', time_vsink);

nccreate(filepath,'source_elem','Dimensions',{'nsources', nsources},'Datatype','double','Format','netcdf4')
ncwrite(filepath,'source_elem', source_elem);

nccreate(filepath,'sink_elem','Dimensions',{'nsinks', nsinks},'Datatype','double','Format','netcdf4')
ncwrite(filepath,'sink_elem', sink_elem);

nccreate(filepath,'vsource','Dimensions',{'nsources', nsources, 'time', ntimes},'Datatype','double','Format','netcdf4')
ncwrite(filepath,'vsource', vsource);

nccreate(filepath,'msource','Dimensions',{'nsources', nsources, 'ntracers', ntracers, 'time', ntimes},'Datatype','double','Format','netcdf4')
ncwrite(filepath,'msource', msource);

nccreate(filepath,'vsink','Dimensions',{'nsinks', nsinks, 'time', ntimes},'Datatype','double','Format','netcdf4')
ncwrite(filepath,'vsink', vsink);

disp('source.nc has been successfully created!')

end















