function msk = def_schism_mask(Mobj, msk_name, def_flag)
% Define a mask on the SCHISM mesh
%
%% Syntax
% msk = def_schism_mask(Mobj)
% msk = def_schism_mask(Mobj, msk_name)
% msk = def_schism_mask(Mobj, msk_name, def_flag)
%
%% Description
% msk = def_schism_mask(Mobj) defines a mask on the mesh grid for SCHISM 
% msk = def_schism_mask(Mobj, msk_name) specifies the mask name for saving
% msk = def_schism_mask(Mobj, msk_name, def_flag) load a defined mask or
% re-define a new mask. 
%
%% Example
% figure
% disp_schism_hgrid(Mobj, 1, 'EdgeAlpha', 0.05, 'LineWidth', 0.5);
% msk = def_schism_mask(Mobj);
% 
% figure
% disp_schism_hgrid(Mobj, 1, 'EdgeAlpha', 0.05, 'LineWidth', 0.5);
% msk = def_schism_mask(Mobj, 'test', 'rebuild');
% 
% figure
% disp_schism_var(Mobj, Mobj.nLevs);
% axis image
% msk = def_schism_mask(Mobj, 'test', 'rebuild');
%
%% Input Arguments
% Mobj --- the mesh object
% msk_name --- the mask name for saving
% def_flag --- re-define a new mask or load a defined mask. 'rebuild' or
% 'load'; Default; def_flag = 'rebuild';
% 
%% Output Arguments
% msk --- a mask vector with logical format.
% 
%% Tips
% A basemap should be created first before you use this function. The
% basemap is usually a water depth map of the model domain, generated by
% 'disp_schism_hgrid.m' function, however, you can also specifiy any other
% basemap such as velocity map, SST map, and so on. It depends on your needs!
%
%% Author Info
% Created by Wenfan Wu, Ocean Univ. of China in 2021. 
% Last Updated on 15 Nov. 2021. 
% Email: wenfanwu@stu.ouc.edu.cn
% 
% See also: drawpolygon and inpolygon

%% Parse inputs
if nargin < 2
    msk_name = 'default';
end
if nargin < 3
    def_flag = 'rebuild';
end

%% Define
msk_file = fullfile(Mobj.aimpath, ['msk_schism_', msk_name, '.mat']);
switch def_flag
    case 'rebuild'
        disp('Draw a polygon on the map to select the released region')
        geo_handle = drawpolygon;
        lonRoi = geo_handle.Position(:,1)';
        latRoi = geo_handle.Position(:,2)';
        close gcf
        
        msk = inpolygon(Mobj.lon, Mobj.lat, lonRoi, latRoi);
        save(msk_file, 'msk')
        disp(['msk_schism_', msk_name, '.mat has been saved into the aimpath'])
    case 'load'
        if exist(msk_file, 'file')
            load(msk_file) %#ok<LOAD> 
        else
            error('No defined mask available!')
        end
end

end